context:
  footer:
    author:
      text: Made ❤ with by
      name: SUMAQ Websites
      link: https://sumaqwebsites.com
    copyright:
      year: ©2021
      name: SUMAQ Websites
      link: https://sumaqwebsites.com
