title: Brand
variants:
  - name: default
    label: Image
    context:
      brand:
        image:
            name: assets/sumaq-logo-dark
            description: Lorem Impsum Logo
  - name: Text
context:
  brand:
    name: Lorem Ipsum
    link: '#'
