title: Brand
status: ready
context:
  brand:
    link: '#'
    name: Lorem Ipsum
variants:
  - name: default
    context:
      brand:
        logo:
          source: assets/sumaq-logo-svg
          name: Lorem Impsum Logo
  - name: text
  - name: logo
    context:
      brand:
        logo:
          source: assets/sumaq-logo-svg
          name: Lorem Impsum Logo
