title: Brand
context:
  brand:
    url: '#'
    name: Lorem Ipsum
variants:
  - name: default
    context:
      brand:
        logo:
          source: assets/sumaq-logo-svg
          description: Lorem Impsum Logo
  - name: text
  - name: logo
    context:
      brand:
        logo:
          source: assets/sumaq-logo-svg
          description: Lorem Impsum Logo
