context:
  text: "Image"
  image:
    source: samples/bike
    name: Lorem ipsum image
variants:
  - name: Caption
    context:
      image:
        description: Lorem ipsum caption
  - name: Responsive
  - name: Caption Responsive
    context:
      image:
        description: Lorem ipsum caption

