context:
  hero:
    pretitle: "Hello, I'm"
    title: SUMAQ websites
    subtitle: 'simple, minimalist y elegant!'
    typewriter:
      text: this is a typewriter
    image:
      name: samples/people/smiling-man
      description: Image from cloudinary samples
    socialNetworks:
      title: Social networks
      items:
        - name: demo@sumaqsites.com
          link: 'mailto:demo@sumaqsites.com'
          icon: icon-email
          abbr: demo@sumaqsites.com
        - name: Github
          link: 'https://github.com/sumaqsites'
          icon: icon-github
          abbr: github
        - name: Website
          link: 'https://sumaqsites.com'
          icon: icon-web
          abbr: web
