status: ready
context:
  address:
    name: 'John Doe'
    lines:
      - Main Street 123
      - Anytown, ST 12345
      - Europe
    phones:
      - +123-456-7890
      - +123-456-7891
    emails:
      - address@mail.com
