status: ready
context:
  coming-soon:
    title: COMING SOON
    text: 'Our website is under construction, follow us for update now!'
    image:
      source: assets/sumaq-logo
      name: Logo Lorem Ipsum
      description: Lorem Ipsum
