status: ready
context:
  menu:
    items:
      - name: Home
        link: '#'
        aria: page
        isActive: true
      - name: Theme
        link: '#'
        aria: false
      - name: Page
        link: '#'
        aria: false
variants:
  - name: vertical
    context:
      menu:
        position: vertical
