context:
  comingSoon:
    title: COMING SOON
    text: 'Our website is under construction, follow us for update now!'
    image:
      name: assets/sumaq-logo-dark
      description: SUMAQ logo image
