name: 'build-npm-package'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm i -g bats
      - run: bats -v
