context:
  languages:
    title: Change language
    items:
      - name: EN
        link: '#'
        aria: page
      - name: ES
        link: '#'
        aria: page
      - name: DE
        link: '#'
        aria: page
